#!/usr/bin/env python3
# ruff: noqa: E501,E701,E702
"""Dump a debug trace + its chat history to a Markdown file.

Usage:
  python scripts/trace_inspect.py 4c8a26bf-778c-4eb1-96c7-1e1d3295e94e
  python scripts/trace_inspect.py --trace-id 4c8a26bf-778c-4eb1-96c7-1e1d3295e94e --out logs/traces
  python scripts/trace_inspect.py <trace_id> --db data/app.db --stdout
  python scripts/trace_inspect.py <trace_id> --with-logs   # + filtered journals + GPU/models in same file

The script is the canonical way to inspect debug traces and chat logs.
Human and AI agents should ALWAYS use it instead of ad-hoc sqlite queries
when searching debug trace logs or chat logs.

Output:
  logs/traces/<trace_id>.md  (default)
  Prints the output path on stdout, plus a short summary.
  With --stdout, also prints the markdown to stdout.
  With --with-logs, appends a filtered journalctl + nvidia-smi/models snapshot
  for the trace's window (cheaper than a separate incident_snapshot when you
  already have the trace open).
"""

from __future__ import annotations

import argparse
import json
import sqlite3
import subprocess
import sys
import urllib.request
from datetime import UTC, datetime
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

DEFAULT_DB = ROOT / "data" / "app.db"
DEFAULT_OUT_DIR = ROOT / "logs" / "traces"

# Try to resolve db path from config.yaml if available
try:
    from app.config import get_config  # type: ignore

    _cfg = get_config()
    _cfg_db = Path(_cfg.db.path)
    CONFIG_DB = _cfg_db if _cfg_db.is_absolute() else ROOT / _cfg_db
    DEFAULT_SWAP_URL = _cfg.llama_swap.base_url
except Exception:
    CONFIG_DB = DEFAULT_DB
    DEFAULT_SWAP_URL = "http://127.0.0.1:8080/v1"

# Routine polling noise filtered from journal sections (same set as incident_snapshot)
_ROUTINE_SUBSTRINGS = [
    "/api/gpu/inventory",
    "/api/debug/summary-status",
    " 304 ",
    "GET /static/",
]


def fmt_ts(ms: int | None) -> str:
    if ms is None:
        return "—"
    try:
        dt = datetime.fromtimestamp(ms / 1000, tz=UTC).astimezone()
        return dt.strftime("%Y-%m-%d %H:%M:%S %Z") + f" ({ms})"
    except Exception:
        return str(ms)


def fmt_duration(started: int | None, ended: int | None, fallback_ms: int | None = None) -> str:
    if started is not None and ended is not None:
        return f"{ended - started} ms"
    if fallback_ms is not None:
        return f"{fallback_ms} ms"
    return "—"


def load_trace(conn: sqlite3.Connection, trace_id: str) -> dict | None:
    conn.row_factory = sqlite3.Row
    row = conn.execute("SELECT * FROM traces WHERE trace_id = ?", (trace_id,)).fetchone()
    if row is None:
        return None
    return dict(row)


def load_spans(conn: sqlite3.Connection, trace_id: str) -> list[dict]:
    rows = conn.execute(
        "SELECT * FROM spans WHERE trace_id = ? ORDER BY started_at ASC, id ASC",
        (trace_id,),
    ).fetchall()
    out: list[dict] = []
    for r in rows:
        d = dict(r)
        try:
            d["data_parsed"] = json.loads(d["data"]) if d["data"] else {}
        except Exception:
            d["data_parsed"] = {"_raw": d["data"]}
        out.append(d)
    return out


def load_chat(conn: sqlite3.Connection, chat_id: str) -> dict | None:
    row = conn.execute("SELECT * FROM chats WHERE id = ?", (chat_id,)).fetchone()
    if row is None:
        return None
    return dict(row)


def load_messages(conn: sqlite3.Connection, chat_id: str) -> list[dict]:
    rows = conn.execute(
        "SELECT id, role, content, model, created_at FROM messages "
        "WHERE chat_id = ? ORDER BY created_at ASC, rowid ASC",
        (chat_id,),
    ).fetchall()
    return [dict(r) for r in rows]


def load_all_traces_for_chat(conn: sqlite3.Connection, chat_id: str) -> list[dict]:
    rows = conn.execute(
        "SELECT trace_id, started_at FROM traces WHERE chat_id = ? ORDER BY started_at ASC",
        (chat_id,),
    ).fetchall()
    return [dict(r) for r in rows]


def build_markdown(
    trace: dict,
    spans: list[dict],
    chat: dict | None,
    messages: list[dict],
    sibling_traces: list[dict] | None,
    db_path: Path,
) -> str:
    trace_id = trace["trace_id"]
    chat_id = trace.get("chat_id")
    lines: list[str] = []

    lines.append(f"# Trace {trace_id}")
    lines.append("")
    lines.append(f"> Generated by `scripts/trace_inspect.py` on {datetime.now().astimezone().strftime('%Y-%m-%d %H:%M:%S %Z')}")
    lines.append(f"> DB: `{db_path}`")
    lines.append("")

    # Overview
    lines.append("## Overview")
    lines.append("")
    lines.append(f"- **trace_id:** `{trace_id}`")
    lines.append(f"- **chat_id:** `{chat_id or '— (no chat)'}`")
    lines.append(f"- **started_at:** {fmt_ts(trace.get('started_at'))}")
    if spans:
        first = min(s["started_at"] for s in spans if s.get("started_at") is not None)
        last = max(s["ended_at"] for s in spans if s.get("ended_at") is not None)
        if first is not None and last is not None:
            lines.append(f"- **wall time:** {last - first} ms (first span start → last span end)")
        lines.append(f"- **spans:** {len(spans)}")
    if chat is not None:
        lines.append(f"- **chat title:** {chat.get('title') or '—'}")
        lines.append(f"- **chat summary:** {chat.get('summary') or '—'}")
        lines.append(f"- **model_override:** {chat.get('model_override') or '—'}")
        lines.append(f"- **messages in chat:** {len(messages)}")
    lines.append("")

    # Chat metadata
    if chat is not None:
        lines.append("## Chat")
        lines.append("")
        lines.append(f"- **id:** `{chat['id']}`")
        lines.append(f"- **title:** {chat.get('title') or '—'}")
        lines.append(f"- **project_id:** {chat.get('project_id') or '—'}")
        lines.append(f"- **model_override:** {chat.get('model_override') or '—'}")
        lines.append(f"- **summary:** {chat.get('summary') or '—'}")
        lines.append(f"- **created_at:** {fmt_ts(chat.get('created_at') * 1000 if chat.get('created_at') and chat['created_at'] < 1e12 else chat.get('created_at'))}")
        lines.append(f"- **updated_at:** {fmt_ts(chat.get('updated_at') * 1000 if chat.get('updated_at') and chat['updated_at'] < 1e12 else chat.get('updated_at'))}")
        if sibling_traces:
            lines.append(f"- **traces for this chat:** {len(sibling_traces)}")
            for t in sibling_traces:
                marker = " ← **this trace**" if t["trace_id"] == trace_id else ""
                lines.append(f"  - `{t['trace_id']}` — {fmt_ts(t['started_at'])}{marker}")
        lines.append("")

    # Messages
    lines.append("## Chat Messages (full history, oldest first)")
    lines.append("")
    if not messages:
        lines.append("_No messages found for this chat._" if chat_id else "_No chat associated with this trace — no messages to show._")
        lines.append("")
    else:
        for i, m in enumerate(messages, start=1):
            role = m["role"]
            model = m.get("model") or ""
            model_str = f" | model=`{model}`" if model else ""
            ts = fmt_ts(m.get("created_at") * 1000 if m.get("created_at") and m["created_at"] < 1e12 else m.get("created_at"))
            lines.append(f"### {i}. [{role}]{model_str} — {ts}")
            lines.append("")
            lines.append(f"- **message_id:** `{m['id']}`")
            lines.append("")
            content = m.get("content") or ""
            lines.append("````markdown")
            lines.append(content)
            lines.append("````")
            lines.append("")

    # Span waterfall
    lines.append("## Spans (waterfall)")
    lines.append("")
    if not spans:
        lines.append("_No spans recorded for this trace._")
        lines.append("")
    else:
        lines.append("| # | stage | started | ended | duration | key fields |")
        lines.append("|---|-------|---------|-------|----------|------------|")
        for idx, s in enumerate(spans, start=1):
            data = s.get("data_parsed", {})
            dur = fmt_duration(s.get("started_at"), s.get("ended_at"), data.get("duration_ms"))
            keys = []
            for k in ("model", "intent", "source", "op", "event", "kind", "error", "tokens_out"):
                if k in data and data[k] not in (None, ""):
                    keys.append(f"{k}={data[k]}")
            if not keys and data:
                for k, v in list(data.items())[:2]:
                    if k == "duration_ms":
                        continue
                    keys.append(f"{k}={str(v)[:40]}")
            key_str = ", ".join(keys) if keys else "—"
            key_str = key_str.replace("|", "\\|")
            lines.append(
                f"| {idx} | `{s['stage']}` | {s.get('started_at') or '—'} | {s.get('ended_at') or '—'} | {dur} | {key_str} |"
            )
        lines.append("")

    # Detailed spans
    lines.append("## Span Details (full `data` JSON)")
    lines.append("")
    if not spans:
        lines.append("_None._")
        lines.append("")
    else:
        for idx, s in enumerate(spans, start=1):
            data = s.get("data_parsed", {})
            lines.append(f"### {idx}. `{s['stage']}` — id={s['id']}")
            lines.append("")
            lines.append(f"- **trace_id:** `{s['trace_id']}`")
            lines.append(f"- **started_at:** {fmt_ts(s.get('started_at'))}")
            lines.append(f"- **ended_at:** {fmt_ts(s.get('ended_at'))}")
            lines.append(f"- **duration:** {fmt_duration(s.get('started_at'), s.get('ended_at'), data.get('duration_ms'))}")
            lines.append("")
            lines.append("```json")
            try:
                pretty = json.dumps(data, indent=2, ensure_ascii=False, default=str)
                if len(pretty) > 40000:
                    pretty = pretty[:40000] + "\n... (truncated, full data is in DB)"
                lines.append(pretty)
            except Exception as e:
                lines.append(f"!! failed to render JSON: {e}")
                lines.append(str(data)[:5000])
            lines.append("```")
            lines.append("")

    # Hints
    lines.append("---")
    lines.append("")
    lines.append("**How to re-query this trace:**")
    lines.append("")
    lines.append("```bash")
    lines.append(f"python scripts/trace_inspect.py {trace_id}")
    lines.append(f"sqlite3 {db_path} \"SELECT stage, data FROM spans WHERE trace_id='{trace_id}' ORDER BY started_at;\"")
    lines.append(f"curl -s http://127.0.0.1:8000/api/debug/trace/{trace_id} | python -m json.tool")
    lines.append("```")
    lines.append("")

    return "\n".join(lines)


def _ms_to_journal_ts(ms: int) -> str:
    import datetime as _dt
    dt = _dt.datetime.fromtimestamp(ms / 1000).astimezone()
    return dt.strftime("%Y-%m-%d %H:%M:%S")


def _filter_routine(text: str) -> tuple[str, int, int]:
    lines_in = text.splitlines()
    kept: list[str] = []
    dropped = 0
    for ln in lines_in:
        if any(pat in ln for pat in _ROUTINE_SUBSTRINGS):
            dropped += 1
            continue
        kept.append(ln)
    return "\n".join(kept), len(kept), dropped


def _collect_log_sections(trace: dict, spans: list[dict], pad_s: int, base_url: str, lines_cap: int = 2000) -> str:
    if spans:
        starts = [s["started_at"] for s in spans if s.get("started_at")]
        ends = [s["ended_at"] for s in spans if s.get("ended_at")]
        lo = min(starts) if starts else trace.get("started_at", 0)
        hi = max(ends) if ends else lo
    else:
        lo = hi = trace.get("started_at", 0)
    lo_pad = lo - pad_s * 1000
    hi_pad = hi + pad_s * 1000
    since_s = _ms_to_journal_ts(lo_pad)
    until_s = _ms_to_journal_ts(hi_pad)

    def _journal(unit: str) -> tuple[str, str]:
        cmd = ["journalctl", "-u", unit, "--since", since_s, "--until", until_s, "--no-pager", "-n", str(lines_cap)]
        try:
            out = subprocess.check_output(cmd, text=True, timeout=10, stderr=subprocess.STDOUT)
            return out, ""
        except subprocess.CalledProcessError as e:
            return e.output or "", f"exit {e.returncode}"
        except FileNotFoundError:
            return "", "journalctl not found"
        except Exception as e:
            return "", str(e)

    app_raw, app_err = _journal("ai-mega-app")
    swap_raw, swap_err = _journal("llama-swap")
    app_filt, app_kept, app_drop = _filter_routine(app_raw) if app_raw else ("", 0, 0)
    swap_filt, swap_kept, swap_drop = _filter_routine(swap_raw) if swap_raw else ("", 0, 0)

    try:
        with urllib.request.urlopen(base_url.rstrip("/") + "/models", timeout=5) as r:
            models_data = json.loads(r.read().decode())
            models_block = json.dumps(models_data, indent=2)
    except Exception as e:
        models_block = f"(failed GET {base_url}/models: {e})"
    try:
        nvsmi = subprocess.check_output(
            ["nvidia-smi", "--query-gpu=index,name,memory.total,memory.free,memory.used,utilization.gpu,temperature.gpu", "--format=csv"],
            text=True, timeout=5,
        )
    except Exception as e:
        nvsmi = f"(nvidia-smi failed: {e})"
    try:
        ps_out = subprocess.check_output(["ps", "aux"], text=True, timeout=5)
        ps_lines = [ln for ln in ps_out.splitlines() if "llama" in ln.lower()]
        ps_block = "\n".join(ps_lines) if ps_lines else "(no llama processes)"
    except Exception as e:
        ps_block = f"(ps failed: {e})"

    out: list[str] = []
    out.append("## Logs (journalctl, filtered) — from --with-logs")
    out.append("")
    out.append(f"> Window: `{since_s}` → `{until_s}`  (pad {pad_s}s around trace, wall {(hi-lo) if hi and lo else 0}ms)")
    out.append(f"> Filtered routine: `{', '.join(_ROUTINE_SUBSTRINGS)}`  — app {app_kept} kept / {app_drop} dropped, swap {swap_kept} kept / {swap_drop} dropped")
    if app_err:
        out.append(f"> app journal err: {app_err}")
    if swap_err:
        out.append(f"> swap journal err: {swap_err}")
    out.append("")
    out.append(f"### llama-swap /v1/models — GET {base_url.rstrip('/')}/models")
    out.append("```json")
    out.append(models_block[:6000])
    out.append("```")
    out.append("")
    out.append("### nvidia-smi")
    out.append("```")
    out.append(nvsmi.strip())
    out.append("```")
    out.append("")
    out.append("### ps aux | grep llama")
    out.append("```")
    out.append(ps_block[:6000])
    out.append("```")
    out.append("")
    out.append(f"### journalctl -u ai-mega-app --since \"{since_s}\" --until \"{until_s}\" (filtered)")
    out.append("```")
    out.append(app_filt[:12000] if app_filt.strip() else "(no non-routine lines in window)")
    out.append("```")
    out.append("")
    out.append(f"### journalctl -u llama-swap --since \"{since_s}\" --until \"{until_s}\" (filtered)")
    out.append("```")
    out.append(swap_filt[:12000] if swap_filt.strip() else "(no non-routine lines in window)")
    out.append("```")
    out.append("")
    return "\n".join(out)


def main() -> int:
    ap = argparse.ArgumentParser(
        description="Dump a debug trace + its chat history to a Markdown file.",
        epilog="Example: python scripts/trace_inspect.py 4c8a26bf-778c-4eb1-96c7-1e1d3295e94e",
    )
    ap.add_argument(
        "trace_id",
        nargs="?",
        help="Trace ID (UUID). Also accepts --trace-id.",
    )
    ap.add_argument("--trace-id", dest="trace_id_opt", default=None, help="Trace ID (alternative to positional)")
    ap.add_argument(
        "--db",
        type=Path,
        default=None,
        help=f"SQLite DB path (default: from config.yaml or {DEFAULT_DB})",
    )
    ap.add_argument(
        "--out",
        type=Path,
        default=None,
        help=f"Output directory (default: {DEFAULT_OUT_DIR})",
    )
    ap.add_argument(
        "--output",
        type=Path,
        default=None,
        dest="out_alias",
        help="Explicit output file path (overrides --out)",
    )
    ap.add_argument(
        "--stdout",
        action="store_true",
        help="Also print the markdown to stdout",
    )
    ap.add_argument(
        "--with-logs",
        action="store_true",
        help="Append filtered journalctl (ai-mega-app + llama-swap) + nvidia-smi/models snapshot for the trace's window",
    )
    ap.add_argument("--log-pad", type=int, default=90, help="Padding seconds before/after trace window for --with-logs (default 90)")
    ap.add_argument("--log-lines", type=int, default=2000, help="journalctl -n per unit for --with-logs (default 2000)")
    ap.add_argument("--base-url", type=str, default=None, help="llama-swap base URL for --with-logs (default from config.yaml)")
    args = ap.parse_args()

    trace_id = (args.trace_id_opt or args.trace_id or "").strip()
    if not trace_id:
        ap.error("trace_id is required (positional or --trace-id)")

    db_path = args.db or CONFIG_DB
    if not db_path.exists():
        print(f"DB not found: {db_path}", file=sys.stderr)
        return 1

    if args.out_alias is not None:
        out_path = args.out_alias
    else:
        out_dir = args.out or DEFAULT_OUT_DIR
        out_dir.mkdir(parents=True, exist_ok=True)
        out_path = out_dir / f"{trace_id}.md"

    conn = sqlite3.connect(str(db_path))
    conn.row_factory = sqlite3.Row
    try:
        trace = load_trace(conn, trace_id)
        if trace is None:
            print(f"Trace not found: {trace_id}", file=sys.stderr)
            recent = conn.execute("SELECT trace_id, chat_id, started_at FROM traces ORDER BY started_at DESC LIMIT 5").fetchall()
            if recent:
                print("Recent traces:", file=sys.stderr)
                for r in recent:
                    print(f"  {r['trace_id']}  chat={r['chat_id']}  {fmt_ts(r['started_at'])}", file=sys.stderr)
            return 1

        spans = load_spans(conn, trace_id)
        chat = None
        messages: list[dict] = []
        siblings: list[dict] | None = None
        if trace.get("chat_id"):
            chat = load_chat(conn, trace["chat_id"])
            if chat is not None:
                messages = load_messages(conn, trace["chat_id"])
            siblings = load_all_traces_for_chat(conn, trace["chat_id"])

        md = build_markdown(trace, spans, chat, messages, siblings, db_path)
        if getattr(args, "with_logs", False):
            base_url = args.base_url or DEFAULT_SWAP_URL
            try:
                log_section = _collect_log_sections(trace, spans, args.log_pad, base_url, lines_cap=args.log_lines)
                md += "\n\n---\n\n" + log_section
            except Exception as e:
                md += f"\n\n---\n\n## Logs (--with-logs failed)\n\n_{e}_\n"

        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_text(md, encoding="utf-8")
        print(f"Wrote {out_path} ({len(md)} chars, {len(spans)} spans, {len(messages)} messages)")
        if args.stdout:
            print("---")
            print(md)
        return 0
    finally:
        conn.close()


if __name__ == "__main__":
    raise SystemExit(main())
