#!/usr/bin/env bash
# Deterministic shell guard for Cursor agents (see docs/CURSOR_RULES.md).
# Cursor passes the pending command as JSON on stdin: {"command": "..."}.
# We echo an allow/deny decision as JSON; a deny cannot be overridden by the model.
# NOTE: verify the exact hook I/O schema against your installed Cursor build —
# it has changed between releases.
cmd="$(cat | python3 -c 'import json,sys; print(json.load(sys.stdin).get("command",""))')"

deny() { echo "{\"permission\": \"deny\", \"userMessage\": \"$1\"}"; exit 0; }

case "$cmd" in
  *"git add ."*|*"git add -A"*|*"git add --all"*)
      deny "Stage files by explicit path (FILE SCOPE), never git add ." ;;
  *"git push"*"--force"*|*"push -f"*)
      deny "Force-push is never allowed." ;;
  *"git push"*|*"git merge"*|*"git rebase"*|*"git cherry-pick"*)
      deny "Merge/push are integrator actions on explicit user request." ;;
  *"llama-swap.yaml"*)
      case "$cmd" in *">"*|*"sed -i"*|*"tee "*)
          deny "llama-swap.yaml is generated by swapgen.py — edit the generator." ;;
      esac ;;
  *"rm -rf"*)
      case "$cmd" in *".pytest-tmp"*|*"node_modules"*) ;; *)
          deny "Recursive delete outside temp dirs requires the user." ;;
      esac ;;
  *"ref_do_not_copy"*)
      deny "ref_do_not_copy/ is human-only reference material." ;;
esac

echo '{"permission": "allow"}'
